common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('petprofile/', views.petprofile, name='petprofile'),
]

mypet/urls.py
from django.urls import path

from . import views

app_name = 'mypet'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

common/models.py
from django.db import models

class Pet(models.Model):
    id=1
    name = "Nokdu"
    age = "2 years old"
    breed = "unknown"
    description = "Cute"


    def __str__(self):
        return self.name

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

mypet/forms.py
from django import forms
from mypet.models import Question,Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        

        

mypet/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseNotAllowed
from .models import Question
from django.utils import timezone
from .forms import QuestionForm,AnswerForm


def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'mypet/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'mypet/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('mypet:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'mypet/question_detail.html', context)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('mypet:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'mypet/question_form.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap.min.css' %}"
    />
    <!-- mypet CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'petprofile.css' %}"
    />
    <title>Hello, myPet!</title>
  </head>
  <body>
    <!-- Navigation bar -->
    {% include "navbar.html" %}
    <!-- embedded detail in base template Start -->
    {% block content %} {% endblock %}
    <!-- embedded detail in base template End -->
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
  </body>
</html>

templates/common/login.html
{% extends "base.html" %} {% block content %}
<div class="container my-3">
  <form method="post" action="{% url 'common:login' %}">
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="mb-3">
      <label for="username">ID</label>
      <input
        type="text"
        class="form-control"
        name="username"
        id="username"
        value="{{ form.username.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        name="password"
        id="password"
        value="{{ form.password.value|default_if_none:'' }}"
      />
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
</div>
{% endblock %}

templates/common/petprofile.html
{% extends "base.html" %} {% block content %}

<div class="mypet_profile">
  <head>
    <title>Pet Profile</title>
  </head>

  <body>
    <h1 class="pet-info">Pet Profile</h1>

    <!-- Pet jpg -->
    <img
      class="pet-image"
      src="https://www.purina.com/sites/default/files/styles/kraken_generic_max_width_240/public/ManxSH_body_6.jpg?itok=pckG_ls2"
      alt="Nokdu"
    />

    <!-- Pet info -->
    <h2 class="pet-info">Nokdu</h2>
    <p class="pet-info">2 years old</p>
    <p class="pet-info">Breed: Unknown</p>
    <p class="pet-info">Description: Cute</p>
  </body>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %} {% block content %}
<div class="container my-3">
  <form method="post" action="{% url 'common:signup' %}">
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="mb-3">
      <label for="username">Username</label>
      <input
        type="text"
        class="form-control"
        name="username"
        id="username"
        value="{{ form.username.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        name="password1"
        id="password1"
        value="{{ form.password1.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="password2">Confirm Password</label>
      <input
        type="password"
        class="form-control"
        name="password2"
        id="password2"
        value="{{ form.password2.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="email">Email</label>
      <input
        type="text"
        class="form-control"
        name="email"
        id="email"
        value="{{ form.email.value|default_if_none:'' }}"
      />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
</div>
{% endblock %}

templates/form_errors.html
<!-- field errors & nonfield errors -->
{% if form.errors %}
<div class="alert alert-danger">
  {% for field in form %}
  <!-- field errors -->
  {% if field.errors %}
  <div>
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
  </div>
  {% endif %} {% endfor %}
  <!-- nonfield errors -->
  {% for error in form.non_field_errors %}
  <div>
    <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}

templates/mypet/question_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <!-- Question -->
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">
        {{ question.content }}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge bg-light text-dark p-2">
          {{ question.create_date }}
        </div>
      </div>
    </div>
  </div>
  <!-- Answer -->
  <h5 class="border-bottom my-3 py-2">
    Here are {{question.answer_set.count}} answers
  </h5>
  {% for answer in question.answer_set.all %}
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">
        {{ answer.content }}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge bg-light text-dark p-2">{{ answer.create_date }}</div>
      </div>
    </div>
  </div>
  {% endfor %}
  <!-- Register Answer -->
  <form
    action="{% url 'mypet:answer_create' question.id %}"
    method="post"
    class="my-3"
  >
    {% csrf_token %}
    <!-- Error Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %} {% if field.errors %}
      <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
      </div>
      {% endif %} {% endfor %}
    </div>
    {% endif %}
    <!-- Error End -->
    <div class="mb-3">
      <label for="content" class="form-label">Answer Detail</label>
      <textarea
        name="content"
        id="content"
        class="form-control"
        rows="10"
      ></textarea>
    </div>
    <input type="submit" value="Register" class="btn btn-primary" />
  </form>
</div>
{% endblock %}

templates/mypet/question_form.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">Register Question</h5>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>
{% endblock %}

templates/mypet/question_list.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <table class="table">
    <thead>
      <tr class="table-dark">
        <th>Num</th>
        <th>Title</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list %} {% for question in question_list %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>
          <a href="{% url 'mypet:detail' question.id %}"
            >{{ question.subject }}</a
          >
        </td>
        <td>{{ question.create_date }}</td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td colspan="3">No Question.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <a href="{% url 'mypet:question_create' %}" class="btn btn-primary"
    >Register</a
  >
</div>
{% endblock %}

templates/navbar.html
<!-- Navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'mypet:index' %}">Mypet</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'common:logout' %}"
            >{{ user.username }} (Logout)</a
          >
          {% else %}
          <a class="nav-link" href="{% url 'common:login' %}">Login</a>
          {% endif %}
        </li>
        <li>
          {% if not user.is_authenticated %}
          <a class="nav-link" href="{% url 'common:signup' %}">Sign Up</a>
          {% endif %}
        </li>
        <li>
          <a class="nav-link" href="{% url 'common:petprofile' %}"
            >MyPet Profile</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>